background_opacity 0.85

font_family      JetBrainsMono Nerd Font
font_size        11.0


# BEGIN_KITTY_THEME
# Everforest Dark Hard
include current-theme.conf
# END_KITTY_THEME
#


enable_audio_bell no

window_padding_width 12
