bind=SUPER,Print,spawn,dms screenshot -d ~/Pictures/Screenshots/ # dms screenshot
bind=Super+Shift,P,spawn_shell,dms ipc call powermenu toggle # dms ipc call powermenu toggle
bind=Super,space,spawn,dms screenshot # dms screenshot
bind=Super+Alt,H,resizewin,-50,+0 # Resize window by -50,+0
bind=Super+Alt,L,resizewin,+50,+0 # Resize window by +50,+0
bind=Super+Ctrl,J,resizewin,+0,+50 # Resize window by +0,+50
bind=Super+Ctrl,K,resizewin,+0,-50 # Resize window by +0,-50
